"""initial catalog and recommendation schema

Revision ID: 001
Revises: 
Create Date: 2026-05-28 18:00:55.237794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('count_likes', sa.Integer(), nullable=True),
    sa.Column('recommends', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=512), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('pinyin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('genre_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('info_zh', sa.Text(), nullable=True),
    sa.Column('info_en', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_categories_name'), 'genre_categories', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('constellation', sa.String(length=50), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('join_time', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('albums',
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('album_lan', sa.String(length=20), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('album_category', sa.String(length=50), nullable=False),
    sa.Column('record_label', sa.String(length=255), nullable=False),
    sa.Column('album_type', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('song_count', sa.Integer(), nullable=False),
    sa.Column('cd_count', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('collects', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('recommends', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('grade_count', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=255), nullable=False),
    sa.Column('pinyin', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('artist_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('num_like', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_meta',
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('pic_address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('info_zh', sa.Text(), nullable=True),
    sa.Column('info_en', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['genre_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_category_id'), 'genres', ['category_id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.create_table('taste_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_text', sa.Text(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=32), nullable=False),
    sa.Column('cache_key', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taste_profiles_cache_key'), 'taste_profiles', ['cache_key'], unique=False)
    op.create_index(op.f('ix_taste_profiles_inputs_hash'), 'taste_profiles', ['inputs_hash'], unique=False)
    op.create_index(op.f('ix_taste_profiles_user_id'), 'taste_profiles', ['user_id'], unique=False)
    op.create_table('album_artist_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('num_like', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_genre_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_meta',
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('pic_address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('artist_genre_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taste_profile_id', sa.Integer(), nullable=False),
    sa.Column('generation_method', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=False),
    sa.Column('judge_model', sa.String(length=64), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taste_profile_id'], ['taste_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_taste_profile_id'), 'recommendations', ['taste_profile_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('songs',
    sa.Column('song_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('cd_serial', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('fav_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('composer', sa.String(length=512), nullable=False),
    sa.Column('songwriters', sa.String(length=512), nullable=False),
    sa.Column('arrangement', sa.String(length=512), nullable=False),
    sa.Column('music_type', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=255), nullable=False),
    sa.Column('hot_part_start', sa.Integer(), nullable=True),
    sa.Column('hot_part_end', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('recommendation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(length=20), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('nearest_neighbors_json', sa.Text(), nullable=True),
    sa.Column('styles_json', sa.Text(), nullable=True),
    sa.Column('judge_cache_key', sa.String(length=32), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('collects', sa.Integer(), nullable=True),
    sa.Column('recommends', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_album_id'), 'recommendation_items', ['album_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_judge_cache_key'), 'recommendation_items', ['judge_cache_key'], unique=False)
    op.create_index(op.f('ix_recommendation_items_recommendation_id'), 'recommendation_items', ['recommendation_id'], unique=False)
    op.create_table('song_artist_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.String(length=20), nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('num_like', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_meta',
    sa.Column('song_id', sa.String(length=20), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_item_id', sa.Integer(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=False),
    sa.Column('song_impression', sa.Text(), nullable=True),
    sa.Column('recommendation_advice', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommendation_item_id', name='uq_feedback_user_item')
    )
    op.create_index(op.f('ix_recommendation_feedback_recommendation_item_id'), 'recommendation_feedback', ['recommendation_item_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    op.create_table('recommendation_quick_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_item_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=16), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommendation_item_id', name='uq_quick_reaction_user_item')
    )
    op.create_index(op.f('ix_recommendation_quick_reactions_recommendation_item_id'), 'recommendation_quick_reactions', ['recommendation_item_id'], unique=False)
    op.create_index(op.f('ix_recommendation_quick_reactions_user_id'), 'recommendation_quick_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_quick_reactions_user_id'), table_name='recommendation_quick_reactions')
    op.drop_index(op.f('ix_recommendation_quick_reactions_recommendation_item_id'), table_name='recommendation_quick_reactions')
    op.drop_table('recommendation_quick_reactions')
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_recommendation_item_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_table('song_meta')
    op.drop_table('song_comments')
    op.drop_table('song_artist_link')
    op.drop_index(op.f('ix_recommendation_items_recommendation_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_judge_cache_key'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_album_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_table('songs')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_taste_profile_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('artist_genre_link')
    op.drop_table('album_meta')
    op.drop_table('album_genre_link')
    op.drop_table('album_comments')
    op.drop_table('album_artist_link')
    op.drop_index(op.f('ix_taste_profiles_user_id'), table_name='taste_profiles')
    op.drop_index(op.f('ix_taste_profiles_inputs_hash'), table_name='taste_profiles')
    op.drop_index(op.f('ix_taste_profiles_cache_key'), table_name='taste_profiles')
    op.drop_table('taste_profiles')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_category_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_table('artist_meta')
    op.drop_table('artist_comments')
    op.drop_table('albums')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_genre_categories_name'), table_name='genre_categories')
    op.drop_table('genre_categories')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
