"""adjust star

Revision ID: 003
Revises: 002
Create Date: 2025-04-26 05:52:49.314945

"""
from typing import Sequence, Union
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_comments', sa.Column('star', sa.Integer(), nullable=False))
    op.drop_column('album_comments', 'review_date')
    op.drop_column('albums', 'star')
    op.add_column('artist_comments', sa.Column('star', sa.Integer(), nullable=False))
    op.drop_column('artist_comments', 'review_date')
    
    # Rename reign to region instead of dropping and adding
    op.alter_column('artists', 'reign', new_column_name='region', existing_type=sa.String(length=50))
    
    op.add_column('song_comments', sa.Column('star', sa.Integer(), nullable=False))
    op.drop_column('song_comments', 'review_date')
    op.add_column('songs', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_column('songs', 'star')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    current_date = datetime.date.today()
    
    op.add_column('songs', sa.Column('star', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('songs', 'order')
    
    # Add review_date with default value
    op.add_column('song_comments', sa.Column('review_date', sa.DATE(), nullable=True))
    # Update with a valid date
    op.execute(f"UPDATE song_comments SET review_date = '{current_date}' WHERE review_date IS NULL")
    # Then make it not nullable - specifying existing type for MySQL
    op.alter_column('song_comments', 'review_date', existing_type=sa.DATE(), nullable=False)
    op.drop_column('song_comments', 'star')
    
    # Rename region back to reign
    op.alter_column('artists', 'region', new_column_name='reign', existing_type=sa.String(length=50))
    
    # Add review_date with default value
    op.add_column('artist_comments', sa.Column('review_date', sa.DATE(), nullable=True))
    # Update with a valid date
    op.execute(f"UPDATE artist_comments SET review_date = '{current_date}' WHERE review_date IS NULL")
    # Then make it not nullable - specifying existing type for MySQL
    op.alter_column('artist_comments', 'review_date', existing_type=sa.DATE(), nullable=False)
    op.drop_column('artist_comments', 'star')
    
    op.add_column('albums', sa.Column('star', mysql.INTEGER(), autoincrement=False, nullable=False))
    
    # Add review_date with default value
    op.add_column('album_comments', sa.Column('review_date', sa.DATE(), nullable=True))
    # Update with a valid date
    op.execute(f"UPDATE album_comments SET review_date = '{current_date}' WHERE review_date IS NULL")
    # Then make it not nullable - specifying existing type for MySQL
    op.alter_column('album_comments', 'review_date', existing_type=sa.DATE(), nullable=False)
    op.drop_column('album_comments', 'star')
    # ### end Alembic commands ###
