"""make artist star nullable

Revision ID: 004
Revises: 003
Create Date: 2025-04-26 17:10:19.376560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_comments', 'star',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('artists', 'region',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'region',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artist_comments', 'star',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
