import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'xiamiu_ui_language';

const translations = {
  zh: {
    discoverMusic: '发现音乐',
    myMusic: '我的音乐',
    searchPlaceholder: '音乐搜索...',
    all: '全部',
    songs: '歌曲',
    albums: '专辑',
    artists: '艺人',
    genres: '风格',
    popular: '热门',
    aiRecommendations: 'AI推荐',
    login: '登录',
    register: '注册',
    logout: '退出',
    languageName: '中文',
    more: '/ 更多',
    noRating: '暂无评分',
    loading: '加载中...',
    loadingAlbums: '正在加载专辑...',
    loadingArtists: '正在加载艺人...',
    loadingGenres: '正在加载风格...',
    loadingResults: '正在加载结果...',
    error: '出错了',
    tryAgain: '重试',
    failedLoadData: '数据加载失败，请稍后再试。',
    failedLoadGenres: '风格加载失败，请稍后再试。',
    noAlbumsFound: '没有找到符合条件的专辑',
    noArtistsFound: '没有找到符合条件的艺人',
    showingRange: ({ start, end, total, item }) => `显示 ${start}-${end}，共 ${total} 个${item}`,
    albumItem: '专辑',
    artistItem: '艺人',
    nameSort: '名称 (A-Z)',
    newestRelease: '最新发行',
    oldestRelease: '最早发行',
    highestRating: '评分最高',
    regionSort: '地区',
    musicStyles: '音乐风格',
    allStyles: '全部风格',
    playlistTitle: '精选歌单',
    playlistComingSoon: '歌单内容即将上线...',
    recommendedSongs: '猜你喜欢',
    newAlbums: '新碟首发',
    chinese: '华语',
    western: '欧美',
    japanese: '日本',
    korean: '韩国',
    noSearchQuery: '请输入搜索关键词',
    searchPrompt: '请输入关键词来搜索艺人、专辑和歌曲。',
    searchError: '搜索出错',
    searchingFor: ({ q, type }) => `正在搜索“${q}”${type ? `（${type}）` : ''}`,
    searchResultsFor: ({ q, type }) => `“${q}”的搜索结果${type ? `（${type}）` : ''}`,
    noResultsFor: ({ q, type }) => `没有找到“${q}”${type ? `（${type}）` : ''}的结果`,
    tryDifferentSearch: '换个关键词试试。',
    allResults: '全部结果',
    dailyRecommendationsKicker: '每日 AI 推荐',
    cachedRecommendationSet: '你的缓存推荐集',
    dailyRecommendationDescription: '基于本地 taste vector、相似专辑证据和缓存 LLM judge 排序。页面加载时不会发起实时模型调用。',
    generated: '生成时间',
    latestCachedRun: '最新缓存结果',
    items: '条目',
    embedding: '向量模型',
    judge: '评审模型',
    method: '方法',
    whyTheseRecommendations: '为什么推荐这些？',
    loadingCachedRecommendations: '正在加载缓存推荐...',
    noRecommendationsYet: '还没有推荐',
    recommendationsCouldNotLoad: '推荐加载失败',
    noRecommendationsHelp: '先评分一些歌曲并运行推荐流程，就能生成第一组每日推荐。',
    backendUnavailableHelp: '请确认后端服务已启动，并且推荐 API 可用。',
    noRecommendationItems: '这组推荐里没有条目',
    noRecommendationItemsHelp: 'API 返回了推荐集，但没有可展示的条目。',
    rank: '排名',
    openAlbum: '打开专辑',
    whyThisFits: '推荐理由',
    noWrittenReason: '这个条目没有返回文字理由。',
    similarRatedAlbums: '相似的已评分专辑',
    noNeighborEvidence: '这个推荐没有附带相似专辑证据。',
    similarity: '相似度',
    quickReaction: '快速反馈',
    interested: '感兴趣',
    saveForLater: '稍后保存',
    skip: '跳过',
    couldNotSaveReaction: '反馈保存失败',
    unknownError: '未知错误',
    rateThisRecommendation: '评价这条推荐',
    submittedEdit: ({ star }) => `已提交 · ${star}★ — 编辑`,
    pickStarsFirst: '请先选择 1-5 星',
    feedbackSaved: '反馈已保存',
    couldNotSaveFeedback: '详细反馈保存失败',
    yourRating: '你的评分',
    songImpression: '歌曲印象',
    recommendationAdvice: '推荐建议',
    editFeedback: '编辑反馈',
    whatDidYouThink: '你觉得这首歌怎么样？',
    tasteProfilePlaceholder: '下次刷新时会写入你的 taste profile。',
    futureAdvice: '对未来推荐有什么建议？',
    judgeContextPlaceholder: '下次运行时会进入 LLM judge 的元上下文。',
    cancel: '取消',
    submitFeedback: '提交反馈',
    llmFit: 'LLM 匹配',
    plays: '播放',
    saves: '收藏',
    recs: '推荐',
    writeComment: '写下你的评论...',
    commentRequired: '评论不能为空',
    submitFailed: '提交失败，请稍后再试。',
    yourRating100: '你的评分 (1-100)：',
    submitting: '提交中...',
    submit: '提交',
    anonymousUser: '匿名用户',
    userNumber: ({ id }) => `用户 #${id}`,
    likes: ({ count }) => `${count} 个赞`,
    delete: '删除',
    rateSong: ({ songName }) => `评价《${songName}》`,
    starCount: ({ count }) => `${count} 星`,
    yourCommentOptional: '你的评论（可选）',
    songThoughtsPlaceholder: '写下你对这首歌的想法...',
    saving: '保存中...',
    save: '保存',
    comments: '评论',
    noCommentsYet: '还没有评论，来做第一个评论的人吧！',
    commentDeleted: '评论已删除',
    commentDeletedDescription: '你的评论已成功删除。',
    commentSubmitted: '评论已提交',
    commentAddedDescription: '你的评论已成功添加。',
    reviewSubmitted: '乐评已提交',
    reviewSubmittedDescription: '你的专辑乐评已成功提交。',
    failedDeleteComment: '删除评论失败，请稍后再试。',
    deleteComment: '删除评论',
    deleteCommentConfirm: '确定要删除这条评论吗？此操作无法撤销。',
    album: '专辑',
    artist: '艺人',
    song: '歌曲',
    releaseDate: '发行日期',
    language: '语种',
    category: '类别',
    rating: '评分',
    recordLabel: '厂牌',
    description: '简介',
    lyrics: '歌词',
    noLyrics: '暂无歌词',
    albumNotFound: '没有找到专辑',
    albumNotFoundHelp: '你要找的专辑不存在。',
    artistNotFound: '没有找到艺人',
    artistNotFoundHelp: '你要找的艺人不存在。',
    songNotFound: '没有找到歌曲',
    songNotFoundHelp: '你要找的歌曲不存在。',
    genreNotFound: '没有找到风格',
    genreNotFoundHelp: '你要找的风格不存在。',
    userNotFound: '没有找到用户',
    userNotFoundHelp: '你要找的用户不存在。',
    loadingAlbumDetails: '正在加载专辑详情...',
    loadingArtistDetails: '正在加载艺人详情...',
    loadingSongDetails: '正在加载歌曲详情...',
    loadingGenreDetails: '正在加载风格详情...',
    loadingUserProfile: '正在加载用户主页...',
    backToAlbums: '返回专辑',
    backToArtists: '返回艺人',
    backToSongs: '返回歌曲',
    backToGenres: '返回风格',
    backToHome: '返回首页',
    noRatingNow: '暂无评分',
    songsCount: ({ count }) => `歌曲 (${count})`,
    commentsCount: ({ count }) => `评论 (${count})`,
    songList: '歌曲列表',
    noSongsForAlbum: '这张专辑暂无歌曲。',
    noCommentsForSong: '这首歌暂无评论。',
    shareAlbumThoughts: '分享你对这张专辑的想法（最多 200 字）',
    shareArtistThoughts: '分享你对这位艺人的想法（最多 200 字）',
    shareSongThoughts: '分享你对这首歌的想法（最多 200 字）',
    loginRequired: '需要登录',
    loginRequiredRateSongs: '登录后才能评价歌曲。',
    failedLoadAlbumDetails: '专辑详情加载失败，请稍后再试。',
    failedLoadArtistDetails: '艺人详情加载失败，请稍后再试。',
    failedLoadSongDetails: '歌曲详情加载失败，请稍后再试。',
    failedLoadGenreDetails: '风格详情加载失败，请稍后再试。',
    failedLoadUserDetails: '用户信息加载失败，请稍后再试。',
    failedLoadCollection: '收藏集加载失败，请稍后再试。',
    ratingSubmitted: '评分已提交',
    ratingSubmittedFor: ({ song }) => `你对《${song}》的评分已提交。`,
    region: '地区',
    discography: ({ artist, count }) => `${artist} 的唱片 (${count})`,
    releaseDateSort: '发行日期',
    albumType: '专辑类型',
    noAlbumsForArtist: '这位艺人暂无专辑。',
    collections: ({ artist }) => `${artist} 收藏集`,
    previous: '上一页',
    next: '下一页',
    pageOf: ({ page, total }) => `第 ${page} / ${total} 页`,
    overview: '概览',
    about: '关于',
    musicActivity: '音乐动态',
    viewAllMusicActivity: '查看全部音乐动态 →',
    joined: '加入时间',
    location: '所在地',
    age: '年龄',
    gender: '性别',
    welcomeBack: ({ name }) => `欢迎回来，${name}！`,
    returnToHome: '返回首页',
    cannotAccessOtherMusic: '你不能访问其他用户的“我的音乐”页面',
    myAlbumComments: '我的专辑评论',
    mySongComments: '我的歌曲评论',
    myArtistComments: '我的艺人评论',
    albumId: ({ id }) => `专辑 ID：${id}`,
    songId: ({ id }) => `歌曲 ID：${id}`,
    artistId: ({ id }) => `艺人 ID：${id}`,
    noAlbumComments: '你还没有评论过任何专辑。',
    noSongComments: '你还没有评论过任何歌曲。',
    noArtistComments: '你还没有评论过任何艺人。',
    starCollection: ({ stars }) => `${stars} 星收藏集`,
    unknownArtist: '未知艺人',
    songCount: ({ count }) => `${count} 首歌`,
    collectionDescription: ({ stars, artist }) => `这里收录了 ${artist} 的所有 ${stars} 星歌曲。`,
    noSongsInCollection: '这个收藏集里还没有歌曲。',
    backToArtistPage: '返回艺人页',
    noArtistsForGenre: '这个风格下暂无艺人。',
    noAlbumsForGenre: '这个风格下暂无专辑。',
    genrePlaceholderArtists: '完整实现后，这里会展示属于该风格的艺人。',
    genrePlaceholderAlbums: '完整实现后，这里会展示属于该风格的专辑。',
    loginToXiamiu: '登录 Xiamiu',
    username: '用户名',
    password: '密码',
    usernameRequired: '请输入用户名',
    passwordRequired: '请输入密码',
    usernamePlaceholder: '输入用户名',
    passwordPlaceholder: '输入密码',
    loggingIn: '登录中...',
    loginFailed: '登录失败，请检查用户名和密码。',
    loginError: '登录时出错，请稍后再试。',
    registrationAdminOnly: '提示：注册目前仅能通过管理员界面完成。',
  },
  en: {
    discoverMusic: 'Discover',
    myMusic: 'My Music',
    searchPlaceholder: 'Search music...',
    all: 'All',
    songs: 'Songs',
    albums: 'Albums',
    artists: 'Artists',
    genres: 'Genres',
    popular: 'Popular',
    aiRecommendations: 'AI Recommendations',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    languageName: 'EN',
    more: '/ More',
    noRating: 'No rating',
    loading: 'Loading...',
    loadingAlbums: 'Loading albums...',
    loadingArtists: 'Loading artists...',
    loadingGenres: 'Loading genres...',
    loadingResults: 'Loading results...',
    error: 'Error',
    tryAgain: 'Try again',
    failedLoadData: 'Failed to load data. Please try again later.',
    failedLoadGenres: 'Failed to load genres. Please try again later.',
    noAlbumsFound: 'No albums found with the selected filters',
    noArtistsFound: 'No artists found with the selected filters',
    showingRange: ({ start, end, total, item }) => `Showing ${start}-${end} of ${total} ${item}`,
    albumItem: 'albums',
    artistItem: 'artists',
    nameSort: 'Name (A-Z)',
    newestRelease: 'Newest release',
    oldestRelease: 'Oldest release',
    highestRating: 'Highest rating',
    regionSort: 'Region',
    musicStyles: 'Music Styles',
    allStyles: 'All Styles',
    playlistTitle: 'Featured Playlists',
    playlistComingSoon: 'Playlist content coming soon...',
    recommendedSongs: 'Recommended Songs',
    newAlbums: 'New Albums',
    chinese: 'Chinese',
    western: 'Western',
    japanese: 'Japan',
    korean: 'Korea',
    noSearchQuery: 'No search query provided',
    searchPrompt: 'Please enter a search term to find artists, albums, and songs.',
    searchError: 'Search Error',
    searchingFor: ({ q, type }) => `Searching for "${q}"${type ? ` in ${type}s` : ''}`,
    searchResultsFor: ({ q, type }) => `Search Results for "${q}"${type ? ` in ${type}s` : ''}`,
    noResultsFor: ({ q, type }) => `No results found for "${q}"${type ? ` in ${type}s` : ''}`,
    tryDifferentSearch: 'Try searching for something else.',
    allResults: 'All Results',
    dailyRecommendationsKicker: 'Daily AI Recommendations',
    cachedRecommendationSet: 'Your cached recommendation set',
    dailyRecommendationDescription: 'Ranked with a local taste vector, nearest-neighbor evidence, and a cached LLM judge. No live model call is made when this page loads.',
    generated: 'Generated',
    latestCachedRun: 'Latest cached run',
    items: 'Items',
    embedding: 'Embedding',
    judge: 'Judge',
    method: 'Method',
    whyTheseRecommendations: 'Why these recommendations?',
    loadingCachedRecommendations: 'Loading cached recommendations...',
    noRecommendationsYet: 'No recommendations yet',
    recommendationsCouldNotLoad: 'Recommendations could not be loaded',
    noRecommendationsHelp: 'Rate some songs and run the recommendation pipeline to generate your first daily set.',
    backendUnavailableHelp: 'Check that the backend is running and the recommendations API is available.',
    noRecommendationItems: 'No items in this recommendation set',
    noRecommendationItemsHelp: 'The API returned a recommendation set without displayable items.',
    rank: 'Rank',
    openAlbum: 'Open album',
    whyThisFits: 'Why this fits',
    noWrittenReason: 'No written reason was returned for this item.',
    similarRatedAlbums: 'Similar to your rated albums',
    noNeighborEvidence: 'No neighbor evidence was attached to this recommendation.',
    similarity: 'Similarity',
    quickReaction: 'Quick reaction',
    interested: 'Interested',
    saveForLater: 'Save for later',
    skip: 'Skip',
    couldNotSaveReaction: 'Could not save reaction',
    unknownError: 'Unknown error',
    rateThisRecommendation: 'Rate this recommendation',
    submittedEdit: ({ star }) => `Submitted • ${star}★ — edit`,
    pickStarsFirst: 'Pick 1-5 stars first',
    feedbackSaved: 'Feedback saved',
    couldNotSaveFeedback: 'Could not save feedback',
    yourRating: 'Your rating',
    songImpression: 'Song impression',
    recommendationAdvice: 'Recommendation advice',
    editFeedback: 'Edit feedback',
    whatDidYouThink: 'What did you think of this song?',
    tasteProfilePlaceholder: 'Flows into your taste profile on the next refresh.',
    futureAdvice: 'Any advice for future recommendations?',
    judgeContextPlaceholder: "Goes into the LLM judge's meta-context next run.",
    cancel: 'Cancel',
    submitFeedback: 'Submit feedback',
    llmFit: 'LLM Fit',
    plays: 'Plays',
    saves: 'Saves',
    recs: 'Recs',
    writeComment: 'Write your comment...',
    commentRequired: 'Comment cannot be empty',
    submitFailed: 'Failed to submit your comment. Please try again.',
    yourRating100: 'Your rating (1-100):',
    submitting: 'Submitting...',
    submit: 'Submit',
    anonymousUser: 'Anonymous User',
    userNumber: ({ id }) => `User #${id}`,
    likes: ({ count }) => `${count} likes`,
    delete: 'Delete',
    rateSong: ({ songName }) => `Rate "${songName}"`,
    starCount: ({ count }) => `${count} ${count === 1 ? 'Star' : 'Stars'}`,
    yourCommentOptional: 'Your Comment (Optional)',
    songThoughtsPlaceholder: 'Write your thoughts about this song...',
    saving: 'Saving...',
    save: 'Save',
    comments: 'Comments',
    noCommentsYet: 'No comments yet. Be the first to comment!',
    commentDeleted: 'Comment deleted',
    commentDeletedDescription: 'Your comment has been deleted successfully.',
    commentSubmitted: 'Comment submitted',
    commentAddedDescription: 'Your comment has been added successfully.',
    reviewSubmitted: 'Review submitted',
    reviewSubmittedDescription: 'Your album review has been submitted successfully.',
    failedDeleteComment: 'Failed to delete the comment. Please try again.',
    deleteComment: 'Delete Comment',
    deleteCommentConfirm: 'Are you sure you want to delete this comment? This action cannot be undone.',
    album: 'Album',
    artist: 'Artist',
    song: 'Song',
    releaseDate: 'Release Date',
    language: 'Language',
    category: 'Category',
    rating: 'Rating',
    recordLabel: 'Record Label',
    description: 'Description',
    lyrics: 'Lyrics',
    noLyrics: 'NO LYRICS FOR NOW',
    albumNotFound: 'Album Not Found',
    albumNotFoundHelp: "The album you're looking for doesn't exist.",
    artistNotFound: 'Artist Not Found',
    artistNotFoundHelp: "The artist you're looking for doesn't exist.",
    songNotFound: 'Song Not Found',
    songNotFoundHelp: "The song you're looking for doesn't exist.",
    genreNotFound: 'Genre Not Found',
    genreNotFoundHelp: "The genre you're looking for doesn't exist.",
    userNotFound: 'User Not Found',
    userNotFoundHelp: "The user you're looking for doesn't exist.",
    loadingAlbumDetails: 'Loading album details...',
    loadingArtistDetails: 'Loading artist details...',
    loadingSongDetails: 'Loading song details...',
    loadingGenreDetails: 'Loading genre details...',
    loadingUserProfile: 'Loading user profile...',
    backToAlbums: 'Back to Albums',
    backToArtists: 'Back to Artists',
    backToSongs: 'Back to Songs',
    backToGenres: 'Back to Genres',
    backToHome: 'Back to Home',
    noRatingNow: 'No rating now',
    songsCount: ({ count }) => `Songs (${count})`,
    commentsCount: ({ count }) => `Comments (${count})`,
    songList: 'Song List',
    noSongsForAlbum: 'No songs available for this album.',
    noCommentsForSong: 'No comments available for this song.',
    shareAlbumThoughts: 'Share your thoughts about this album (200 characters max)',
    shareArtistThoughts: 'Share your thoughts about this artist (200 characters max)',
    shareSongThoughts: 'Share your thoughts about this song (200 characters max)',
    loginRequired: 'Login required',
    loginRequiredRateSongs: 'You need to log in to rate songs.',
    failedLoadAlbumDetails: 'Failed to load album details. Please try again later.',
    failedLoadArtistDetails: 'Failed to load artist details. Please try again later.',
    failedLoadSongDetails: 'Failed to load song details. Please try again later.',
    failedLoadGenreDetails: 'Failed to load genre details. Please try again later.',
    failedLoadUserDetails: 'Failed to load user details. Please try again later.',
    failedLoadCollection: 'Failed to load collection. Please try again later.',
    ratingSubmitted: 'Rating submitted',
    ratingSubmittedFor: ({ song }) => `Your rating for "${song}" has been submitted.`,
    region: 'Region',
    discography: ({ artist, count }) => `${artist} Discography (${count})`,
    releaseDateSort: 'Release Date',
    albumType: 'Album Type',
    noAlbumsForArtist: 'No albums found for this artist.',
    collections: ({ artist }) => `${artist} Collections`,
    previous: 'Previous',
    next: 'Next',
    pageOf: ({ page, total }) => `Page ${page} of ${total}`,
    overview: 'Overview',
    about: 'About',
    musicActivity: 'Music Activity',
    viewAllMusicActivity: 'View all music activity →',
    joined: 'Joined',
    location: 'Location',
    age: 'Age',
    gender: 'Gender',
    welcomeBack: ({ name }) => `Welcome back, ${name}!`,
    returnToHome: 'Return to Home',
    cannotAccessOtherMusic: "You cannot access another user's My Music page",
    myAlbumComments: 'My Album Comments',
    mySongComments: 'My Song Comments',
    myArtistComments: 'My Artist Comments',
    albumId: ({ id }) => `Album ID: ${id}`,
    songId: ({ id }) => `Song ID: ${id}`,
    artistId: ({ id }) => `Artist ID: ${id}`,
    noAlbumComments: "You haven't commented on any albums yet.",
    noSongComments: "You haven't commented on any songs yet.",
    noArtistComments: "You haven't commented on any artists yet.",
    starCollection: ({ stars }) => `${stars} Star Collection`,
    unknownArtist: 'Unknown Artist',
    songCount: ({ count }) => `${count} songs`,
    collectionDescription: ({ stars, artist }) => `This collection contains all ${stars}-star rated songs by ${artist}.`,
    noSongsInCollection: 'No songs found in this collection.',
    backToArtistPage: 'Back to Artist Page',
    noArtistsForGenre: 'No artists available for this genre.',
    noAlbumsForGenre: 'No albums available for this genre.',
    genrePlaceholderArtists: 'This is a placeholder. In a complete implementation, this would show artists in this genre.',
    genrePlaceholderAlbums: 'This is a placeholder. In a complete implementation, this would show albums in this genre.',
    loginToXiamiu: 'Login to Xiamiu',
    username: 'Username',
    password: 'Password',
    usernameRequired: 'Username is required',
    passwordRequired: 'Password is required',
    usernamePlaceholder: 'Enter your username',
    passwordPlaceholder: 'Enter your password',
    loggingIn: 'Logging in...',
    loginFailed: 'Login failed. Please check your credentials.',
    loginError: 'An error occurred during login. Please try again.',
    registrationAdminOnly: 'Note: Registration is currently only available through the admin interface.',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('zh');

  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === 'zh' || saved === 'en') {
      setLanguage(saved);
    }
  }, []);

  const value = useMemo(() => {
    const setAndStore = (nextLanguage) => {
      setLanguage(nextLanguage);
      window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    };

    const t = (key, params) => {
      const entry = translations[language]?.[key] ?? translations.zh[key] ?? key;
      return typeof entry === 'function' ? entry(params || {}) : entry;
    };

    return {
      language,
      isChinese: language === 'zh',
      setLanguage: setAndStore,
      toggleLanguage: () => setAndStore(language === 'zh' ? 'en' : 'zh'),
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
