# Generated by Django 3.0.7 on 2021-01-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumID', models.CharField(db_column='albumID', max_length=20, primary_key=True, serialize=False)),
                ('albumName', models.CharField(db_column='albumName', max_length=255)),
                ('albumLan', models.CharField(db_column='albumLan', max_length=10)),
                ('releaseDate', models.DateField(db_column='releaseDate')),
                ('albumCategory', models.CharField(db_column='albumCategory', max_length=20)),
                ('recordLabel', models.CharField(db_column='recordLabel', max_length=50)),
                ('star', models.CharField(db_column='star', max_length=10)),
                ('myCmt', models.TextField(db_column='myCmt')),
                ('listenDate', models.DateField(db_column='listenDate')),
            ],
            options={
                'db_table': 'Album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistID', models.CharField(db_column='artistID', max_length=20, primary_key=True, serialize=False)),
                ('artistName', models.CharField(db_column='artistName', max_length=50)),
                ('genreReign', models.CharField(db_column='artistReign', max_length=50)),
            ],
            options={
                'db_table': 'Artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.CharField(db_column='songID', max_length=20, primary_key=True, serialize=False)),
                ('songName', models.CharField(db_column='songName', max_length=255)),
                ('star', models.CharField(db_column='star', max_length=10)),
                ('myCmt', models.TextField(db_column='myCmt')),
            ],
            options={
                'db_table': 'Song',
                'managed': False,
            },
        ),
    ]
