# Generated by Django 3.0.7 on 2021-06-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiamiu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreID', models.IntegerField(db_column='genreID', primary_key=True, serialize=False)),
                ('genreName', models.CharField(db_column='genreName', max_length=50)),
                ('genreInfo', models.TextField(db_column='genreInfo')),
            ],
            options={
                'db_table': 'Genre',
                'managed': False,
            },
        ),
    ]
